context:
  version: 0.14.8

package:
  name: procs
  version: ${{ version }}

source:
  url: https://github.com/dalance/procs/archive/v${{ version }}.tar.gz
  sha256: b9cf37275bdf1c03786a035c1cd495a93cbf94406eb8c261825d1fd59dcfd61d

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - procs --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Modern replacement for ps written by Rust
  homepage: https://github.com/dalance/procs
  repository: https://github.com/dalance/procs

extra:
  recipe-maintainers:
    - danielnachun
